### ISSUE TITLE
prober fails (and halts installation) if an inactive raid is present on the system

### ISSUE THREAD

**Issue by nkshirsagar** [canonical/probert#125]
This happens with the manual ISO installation or using an auto install input. When there is an inactive RAID present at the server subquity will fail with:

~~~
2022-10-13 20:06:12,262 ERROR root:39 finish: subiquity/Filesystem/_probe/probe_once: FAIL: 'MD_LEVEL'
2022-10-13 20:06:12,262 ERROR block-discover:442 block probing failed restricted=False
Traceback (most recent call last):
File "/snap/subiquity/3698/lib/python3.8/site-packages/subiquity/server/controllers/filesystem.py", line 436, in _probe
await asyncio.wait_for(self._probe_once_task.task, timeout)
File "/snap/subiquity/3698/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
return fut.result()
File "/snap/subiquity/3698/lib/python3.8/site-packages/subiquitycore/context.py", line 148, in decorated_async
return await meth(self, **kw)
File "/snap/subiquity/3698/lib/python3.8/site-packages/subiquity/server/controllers/filesystem.py", line 404, in _probe_once
storage = await run_in_thread(
File "/snap/subiquity/3698/lib/python3.8/site-packages/subiquitycore/async_helpers.py", line 46, in run_in_thread
return await loop.run_in_executor(None, func, *args)
File "/snap/subiquity/3698/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/snap/subiquity/3698/lib/python3.8/site-packages/subiquitycore/prober.py", line 59, in get_storage
return Storage().probe(probe_types=probe_types)
File "/snap/subiquity/3698/lib/python3.8/site-packages/probert/storage.py", line 186, in probe
probed_data[ptype] = pfunc(context=self.context)
File "/snap/subiquity/3698/lib/python3.8/site-packages/probert/raid.py", line 143, in probe
'raidlevel': device['MD_LEVEL'],
File "/snap/subiquity/3698/lib/python3.8/site-packages/pyudev/device/_device.py", line 957, in __getitem__
return self.properties.__getitem__(prop)
File "/snap/subiquity/3698/lib/python3.8/site-packages/pyudev/device/_device.py", line 1084, in __getitem__
raise KeyError(prop)
KeyError: 'MD_LEVEL'
2022-10-13 20:06:12,266 INFO subiquitycore.common.errorreport:406 saving crash report 'block probing crashed with KeyError' to /var/crash/1665691572.265830994.block_probe_fail.crash
2022-10-13 20:06:12,266 INFO root:39 start: subiquity/ErrorReporter/1665691572.265830994.block_probe_fail/add_info:

# lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
vda 252:0 0 10G 0 disk
vdb 252:16 0 10G 0 disk
vdc 252:32 0 20G 0 disk
└─md127 9:127 0 0B 0 md
vdd 252:48 0 20G 0 disk
└─md127 9:127 0 0B 0 md

# cat /proc/mdstat
Personalities : [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4] [raid10]
md127 : inactive vdd[3](S) vdc[2](S)
41908224 blocks super 1.2

unused devices: <none>

# mdadm info -q all /dev/md127
mdadm: An option must be given to set the mode before a second device
(all) is listed
root@ubuntu-server:/var/log/installer# udevadm info -q all /dev/md127
P: /devices/virtual/block/md127
N: md127
L: 0
E: DEVPATH=/devices/virtual/block/md127
E: DEVNAME=/dev/md127
E: DEVTYPE=disk
E: DISKSEQ=15
E: MAJOR=9
E: MINOR=127
E: SUBSYSTEM=block
E: USEC_INITIALIZED=1641118
E: SYSTEMD_READY=0
E: UDISKS_MD_DEVICES=2
E: UDISKS_MD_METADATA=1.2
E: UDISKS_MD_UUID=2f49b5ef:1c06a172:2dcfd766:90df00b0
E: UDISKS_MD_DEVNAME=ubuntu-server:127
E: UDISKS_MD_NAME=ubuntu-server:127
E: UDISKS_MD_DEVICE_dev_vdc_ROLE=spare
E: UDISKS_MD_DEVICE_dev_vdc_DEV=/dev/vdc
E: UDISKS_MD_DEVICE_dev_vdd_ROLE=spare
E: UDISKS_MD_DEVICE_dev_vdd_DEV=/dev/vdd
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
~~~

udevadm does not show the MD_LEVEL information on an inactive RAID, which breaks the probe. The fix could be to simply not return that information if its not exported by udev. We are breaking here - https://github.com/canonical/probert/blob/master/probert/raid.py#L143

This could also be a potential problem - 
https://github.com/canonical/probert/blob/master/probert/raid.py#L123

If udev could export MD_LEVEL for inactive raid arrays too that would help fix this too, but I am not sure if that is possible.

**Comment by ogayot** [comment]
Same root cause (with potentially different symptoms):

https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1975860

**Comment by nkshirsagar** [comment]
It's expected behavior for MD_LEVEL not to be set for inactive raid devices. 

~~~
# do not edit this file, it will be overwritten on update

SUBSYSTEM!="block", GOTO="md_end"

# handle md arrays
ACTION!="add|change", GOTO="md_end"
KERNEL!="md*", GOTO="md_end"

# partitions have no md/{array_state,metadata_version}, but should not
# for that reason be ignored.
ENV{DEVTYPE}=="partition", GOTO="md_ignore_state"

# container devices have a metadata version of e.g. 'external:ddf' and
# never leave state 'inactive'
ATTR{md/metadata_version}=="external:[A-Za-z]*", ATTR{md/array_state}=="inactive", GOTO="md_ignore_state" <==
TEST!="md/array_state", ENV{SYSTEMD_READY}="0", GOTO="md_end"
ATTR{md/array_state}=="|clear|inactive", ENV{SYSTEMD_READY}="0", GOTO="md_end"
LABEL="md_ignore_state"

IMPORT{program}="/sbin/mdadm --detail --export $devnode"
ENV{DEVTYPE}=="disk", ENV{MD_NAME}=="?*", SYMLINK+="disk/by-id/md-name-$env{MD_NAME}", OPTIONS+="string_escape=replace"
<SNIP>

LABEL="md_end"
~~~

So IMPORT{program}="/sbin/mdadm --detail --export $devnode" is skipped if the array is inactive.

**Comment by dbungert** [comment]
Would you provide steps on how to deactivate the md raid?  When I've done it the entry disappears entirely.

**Comment by nkshirsagar** [comment]
Hi @dbungert ,

You can start it 'incrementally', after you stop it. This leaves it inactive but the /dev entry is present.
 
~~~

root@bronzor:/home/ubuntu# mdadm --assemble /dev/md127 /dev/sdc1 /dev/sdc2
mdadm: /dev/md127 has been started with 2 drives.
root@bronzor:/home/ubuntu# cat /proc/mdstat 
Personalities : [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4] [raid10] 
md127 : active raid1 sdc1[0] sdc2[1]
      52395008 blocks super 1.2 [2/2] [UU]
      [==========>..........]  resync = 50.4% (26409536/52395008) finish=6.4min speed=67648K/sec
      
unused devices: <none>
root@bronzor:/home/ubuntu# cat /proc/mdstat 
Personalities : [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4] [raid10] 
md127 : active raid1 sdc1[0] sdc2[1]
      52395008 blocks super 1.2 [2/2] [UU]

root@bronzor:/home/ubuntu# mdadm --incremental /dev/sdc1
mdadm: /dev/sdc1 attached to /dev/md/127, not enough to start safely.

root@bronzor:/home/ubuntu# cat /proc/mdstat 
Personalities : [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4] [raid10] 
md127 : inactive sdc1[0](S)
      52395008 blocks super 1.2
       
unused devices: <none>
root@bronzor:/home/ubuntu# udevadm info -q all /dev/md127
P: /devices/virtual/block/md127
N: md127
L: 0
E: DEVPATH=/devices/virtual/block/md127
E: DEVNAME=/dev/md127
E: DEVTYPE=disk
E: DISKSEQ=29
E: MAJOR=9
E: MINOR=127
E: SUBSYSTEM=block
E: USEC_INITIALIZED=1740959977082
E: SYSTEMD_READY=0
E: UDISKS_MD_DEVICES=1
E: UDISKS_MD_METADATA=1.2
E: UDISKS_MD_UUID=112304ba:e96d88ea:0694ceeb:db93245f
E: UDISKS_MD_DEVNAME=127
E: UDISKS_MD_NAME=bronzor:127
E: UDISKS_MD_DEVICE_dev_sdc1_ROLE=spare
E: UDISKS_MD_DEVICE_dev_sdc1_DEV=/dev/sdc1
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
~~~

**Comment by nkshirsagar** [comment]
The fix through https://github.com/canonical/probert/pull/124 has been merged
